apiVersion: v1
kind: Namespace
metadata:
  name: sample
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: sample
  labels:
    app: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: dok-sample:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 8080
        command: ["/opt/server/bin/serve"]
        args: ["/var/lib/storage", "0.0.0.0:8080"]
        volumeMounts:
        - mountPath: /var/lib/storage
          name: storage
        imagePullPolicy: Never
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: worker-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: sample
  labels:
    app: worker
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: worker
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: worker-pvc
   namespace: sample
   annotations:
     volume.beta.kubernetes.io/storage-class: standard
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 1Gi